name: SafeChat
version: 1.1.0
author: Luminous-Coder

main: lumynous.safechat.Main
api-version: 1.19

commands:
  reload-config:
    description: Reload the configurations.
    permission: bukkit.command.reload
  msg:
    aliases:
      - tell
      - w
    description: Send a private message to another player.
    usage: /msg <player name or UUID> <message>
